### ISSUE TITLE
Wind direction wont change, stays at W

### ISSUE THREAD

**Issue by Jake152** [Jake152/Java-weather-forecaster#1]
In the drive when you go to change the wind direction, it doesn't change properly and always displays W. This is in the weather class.

**Comment by TuckerKent1** [comment]
Fixed. 

I changed the if statement to a switch statement. Not exactly sure what was causing it, but I am thinking that it had to do with the OR conditionals that were in the if statement.

Also found and fixed a bug throwing an error with the String.format method in the toString() of the Weather class
